IMAGE1 = "debian/bookworm64"

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  NodeType1 = 1
  (1..NodeType1).each do |no1_id|

    config.vm.define "vmbox1#{no1_id}" do |vmbox1|
      vmbox1.vm.box = IMAGE1
      vmbox1.vm.hostname = "vmbox1#{no1_id}"
      vmbox1.vm.network "private_network", ip: "192.168.56.11#{no1_id}"
      vmbox1.vm.provider "virtualbox" do |v|
        v.name = "vbox#{no1_id}"
        v.memory = 1024
        v.cpus = 1
      end
    end
  end

  NodeType2 = 2
  (1..NodeType2).each do |no2_id|
    config.vm.define "vmbox1#{no2_id}" do |vmbox2|
      vmbox2.vm.box = IMAGE1
      vmbox2.vm.hostname = "vmbox1#{no2_id}"
      vmbox2.vm.network "private_network", ip: "192.168.56.11#{no2_id}"
      vmbox2.vm.provider "virtualbox" do |v|
        v.name = "vbox#{no2_id}"
        v.memory = 1024
        v.cpus = 1
      end
    end
  end  
end
