---
# tasks file for preparing

- name: update and upgrade os
  ansible.builtin.apt:
    update_cache: yes
    upgrade: safe
    autoclean: yes
    autoremove: yes

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"


- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - vim
    - curl
    - wget
    - git
    - htop
    - iotop
    - bash-completion
    - iptables-persistent
    - net-tools
    - tmux
